####################      general      ####################
spring.application.name = BATCH
# disable the server 
spring.main.web-application-type=none
spring.profiles.active =dev
app.version = V0.0.6

person.data = C:/Users/yassi/Desktop/My Tutorials/batch-annotations/data/person_data.csv