####################      general      ####################
server.port = 8080
server.forward-headers-strategy=FRAMEWORK

####################       log4j2      ####################
logging.path = ./logs



####################       batch       ####################
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
spring.main.allow-bean-definition-overriding=true
app.async.corePoolSize= 8
app.async.maximumPoolSize= 8
app.async.queueCapacity = 100
app.async.keepAliveTime= 1

####################        DBs        ####################

spring.local.datasource.url = jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
spring.local.datasource.username = root
spring.local.datasource.password = rootroot
spring.local.datasource.driver-class-name = com.mysql.cj.jdbc.Driver


####################        JPA        ####################
# local

spring.local.jpa.hibernate.ddl-auto = update
spring.local.jpa.show-sql=false
spring.local.jpa.database-platform= org.hibernate.dialect.MySQL8Dialect
spring.local.jpa.generate-ddl= false
spring.local.sql.init.mode=always

